#!/usr/bin/env python3
"""Generate public/content/upanishads/brahmasutra.json"""

import json, os
from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate

def dev(iast_text):
    return transliterate(iast_text, sanscript.IAST, sanscript.DEVANAGARI)

# ── All 555 Brahmasūtras (IAST), organised by adhyāya.pāda ─────────────────
# Source: GRETIL / Thibaut's translation (public domain)
SUTRAS = {
    # Adhyāya 1
    (1,1): [
        ("athāto brahmajijñāsā", "Now, therefore, the inquiry into Brahman."),
        ("janmādyasya yataḥ", "From which proceed the birth, etc., of this (world)."),
        ("śāstrayonitvāt", "Because scripture is the source of right knowledge."),
        ("tat tu samanvayāt", "But that (Brahman is to be known from scripture) on account of its being the connected purport (of all Vedānta-texts)."),
        ("īkṣaternāśabdam", "The omniscient Brahman cannot be the non-intelligent pradhāna, because the quality of seeing is mentioned."),
        ("gauṇaścennātmaśabdāt", "But if (the Lord be taken) in a secondary sense, (we say) not so, on account of the term 'Self.'"),
        ("tanniṣṭhasya mokṣopadeśāt", "And on account of the teaching of freedom from it (saṃsāra) to him who is devoted to that."),
        ("heyatvāvacanācca", "And because non-rejection (of the Lord as the cause) is taught."),
        ("svāpyayāt", "On account of his (the Self's) merging in (deep sleep)."),
        ("gatisamānyāt", "On account of the uniformity of view (in all Vedānta-texts)."),
        ("śrutatvācca", "And because it is so stated in scripture."),
        ("ānandamayo'bhyāsāt", "The ānandamaya is Brahman, on account of repetition (of the word 'bliss')."),
        ("vikāraśabdānneti cenna prācuryāt", "If it be said (that ānandamaya is) not (Brahman) on account of the affix (maya), we deny this on account of abundance (of bliss being Brahman's characteristic)."),
        ("taddhetuvyapadeśācca", "And because it is stated to be the cause thereof."),
        ("māntramāhikamupadadeśe'śabdamprasiddheḥ", "The mantra and arthavāda (corroborative passage) refer to a different entity from Brahman on account of (another) meaning being stated, and because something not mentioned is here taught."),
        ("netaro'nupapatteḥ", "Not any other one, because that is impossible."),
        ("bhedavyapadeśācca", "And on account of distinction being declared."),
        ("kāmācca nānumānāpekṣā", "And on account of (the word) desire, there is no need of inference."),
        ("asminnasya ca tadyogaṃ śāsti", "And scripture teaches the relation of this (individual soul) to that (Brahman)."),
        ("antastaddharmopadeśāt", "The internal (ruler) is Brahman, on account of the attributes of that (Brahman) being taught."),
        ("na ca smartamataduktaṃ", "And because what is smṛti-text (of the Sāṃkhyas) does not teach the same."),
        ("śreyaḥparigrahaśca nityatvācca", "And because the (Vedānta) texts embrace the most excellent (view), and because of eternality."),
        ("prāṇaḥ", "The prāṇa (in the Chāndogya) is Brahman."),
        ("bhedātiti cennaikasya ubhayathā", "If it be said (that prāṇa is not Brahman) on account of difference; we reply that in one (being) both are found."),
        ("vākyānvayāt", "On account of the connection of the text."),
        ("prakaraṇāt", "On account of the topic."),
        ("sthānādibyaśca", "And on account of place and so on."),
        ("sarvāpekṣā ca yajñādiśruter aśvavanmānāt", "And the all-requirement is gathered from the scriptural statement of sacrifice and so on, as in the case of a horse."),
        ("śrutyuktābhyāṃ guṇadvayācca", "And on account of the two qualities mentioned in the text."),
        ("śabda iti cennataḥ prabhavāt pratyakṣānumānābhyām", "If it be said that Brahman is not (the cause) on account of (the word) 'origin,' we deny this, because (Brahman is) the origin of these (two, viz., speech and the rest) as shown by perception and inference."),
        ("ata eva ca nityatvam", "And from this very same reason, eternality."),
    ],
    (1,2): [
        ("sarvatra prasiddhyupadeśāt", "On account of teaching the well-known (Brahman) everywhere."),
        ("vivakṣitaguṇopapatteścaiva", "And because the qualities which are intended are appropriate."),
        ("anupapattestu na śāreere", "But on account of impossibility, not (the soul in) the body."),
        ("karmakartṛvyapadeśācca", "And on account of the statement of the agent and the object of action."),
        ("śabdaviśeṣāt", "On account of the specific word."),
        ("smṛtibhyaśca", "And on account of smṛti texts."),
        ("arabhyate aṇumātrasya", "It (the individual soul) is of atomic size, as is known from scripture."),
        ("utkrāntergatigrahaṇāt", "On account of the going out (of the soul at death) and coming in being mentioned."),
        ("svenopadhidhṛte ca", "And because it is connected with its own limiting adjunct."),
        ("jñopadhiḥ", "The intelligent limiting adjunct (is understood)."),
        ("ata eva ca nityatvam", "And for this very reason eternality (follows)."),
        ("puṃstvādivat tvasya sato'bhivyaktiyogāt", "But as in the case of maleness, etc., the manifestation of what already exists."),
        ("nityopalabdhyanupalabdhiprasaṅgo'nyataraniyamo vānyathā", "Otherwise there would be necessary either eternal perception or eternal non-perception, or the limitation of one of them."),
        ("kartrā paramāt taddhi", "From the highest, because that is stated."),
        ("viparyayeṇa tu kramas tadalpatvaṃ ca tatha hi darśayati", "But the order is reversed and the smallness of the pradhāna; thus it is shown."),
        ("upasaṃhāraḥ tat darśanāt", "The reference is to that on account of that being seen."),
        ("etenottara api vyākhyātāḥ", "By this are explained the higher ones also."),
        ("na vilakṣaṇatvādasya tathātvaṃ ca śabdāt", "Not on account of the absence of special attributes, and because of the scriptural word."),
        ("dṛśyate tu", "But it is seen."),
        ("tadadhīnathā taddarshanath", "And because of dependence on that, that (Brahman) being seen."),
        ("asminnasya ca tadyogaṃ śāsti", "And scripture teaches the relation of this to that."),
        ("prāṇastattvam", "Prāṇa is that Brahman."),
        ("na vāyvapadeśādatonyā vāyor avasthiteḥ", "Not on account of the designation of air; (Brahman is) distinct from air, because of the existence of another (than air)."),
        ("bheṣajāt tatsambandhācca", "And because of the remedy, and of connection with that."),
        ("saptānnā brahmano vicāraṃ", "The seven foods are Brahman's."),
        ("kāmācca nānumānāpekṣā", "And on account of desire there is no need of inference."),
        ("anena sarvagatatvamāyāmaśabdāt", "By this (Brahman) the all-pervasiveness; on account of the word indicating extension."),
        ("phalaṃ tatpramāṇatvāt", "The fruit (of actions) is from that (Brahman); on account of Brahman being the standard."),
        ("śruter māpadeśaśca", "And on account of 'māpadeśa' in scripture."),
        ("dṛṣṭāntaśca", "And there is a parallel case."),
        ("prāṇādibhyaḥ", "On account of prāṇa and the rest."),
        ("na vayasyapi nirāktiḥ", "Not also the other, because of non-mention."),
        ("anyathānumitau ca jaiminiḥ", "If otherwise, inference also is (without foundation); so Jaimini (thinks)."),
        ("samānāyāṃ ca", "And because there is a like (description in another text)."),
        ("na sāmānyādapyupalabdheḥ mūrtatvān nānadravyatvaśruteḥ", "Not even on account of similarity being known; on account of corporeal nature; and because scripture (teaches Brahman to be) not different from the individual soul."),
        ("buddhyarthapādavyapadeśācca", "And because the feet are spoken of as for intelligence."),
        ("sarvabhāvāt", "Because of the being everything."),
    ],
    (1,3): [
        ("dyubhvādyāyatanaṃ svayaṃbhuvyapadeśāt", "The abode of sky, earth, etc., is Brahman, on account of the term 'self-luminous' being applied."),
        ("muktopasṛpyavyapadeśācca", "And because it is stated to be that which the released soul reaches."),
        ("nānumānametatapṛthagdṛṣṭatvādupadeśādca", "This is not mere inference, because (Brahman) is seen separately (from matter) and on account of teaching."),
        ("hānau tūpāyanambhyāsāt", "On the removal (of ignorance), on account of the teaching (of union with Brahman)."),
        ("darśanācca", "And because of being seen."),
        ("etena yogaḥ pratyuktaḥ", "By this the yoga (of the Sāṃkhyas) is refuted."),
        ("na ca kāryātmaikyam udbhavapralayābhyāṃ satataṃ ca tasya", "And the effect is not identical (with Brahman), because of origin and destruction; and because it always thus (remains in conjunction with the effect)."),
        ("asad iti cen na pratisedhamatrādhikaraṇam", "If it be said (that Brahman cannot be) non-existent, we deny this: the meaning is that the present subject (i.e., Brahman) is not (something to be negated)."),
        ("na vilakṣaṇatvādasya tathātvam", "Not on account of the difference (of origin), is it similarly."),
        ("māyāmātraṃ tu kārtsnyenānabhivyaktasvarūpatvāt", "But (it is) mere māyā, on account of the real nature not being fully manifested."),
        ("sūcakañcahi śruter ācāryasya", "And because there is a pointer (to the contrary view), which is (expressed) in the teacher's own text."),
        ("anyabhāvavyavṛtteśca", "And on account of the negation of a different nature."),
        ("rūpopanyāsācca", "And on account of the mention of form."),
        ("vaiśeṣyāt tu tadvādastadbhāvabhāvitvāt", "But the text (has its force) on account of the distinction, since becoming follows on the becoming of that."),
        ("darśayati ca", "And scripture shows."),
        ("prakāśavaccāvaişeşyaṃ prakāśasca karmanyabhyāsāt", "And there is no difference as in the case of light; and light also, on account of repetition in the text, (is meant to be Brahman)."),
        ("ata eva ca nityatvam", "And from this very reason follows eternality."),
        ("api ca smaryate", "And it is also mentioned in smṛti."),
        ("śabda iti cen nātaḥ prabhavāt", "If it be said, on account of (the word) 'word,' not so, because (Brahman is) the origin thereof."),
        ("yāvaddikṣaṇaṃ tadvyapadeśaḥ", "As long as the qualification lasts, so long (lasts) the designation."),
        ("darśanācca", "And because it is seen."),
        ("parāt tu tacchrutes tanmātram", "But from the highest (Brahman), that being taught; only that."),
        ("atra api caivameva", "Here also in the same way."),
        ("aupamyāt", "On account of the comparison."),
        ("amuṃ vyomatatvam", "That (Brahman) has the nature of ether."),
        ("ātmā", "Brahman is the Self."),
        ("darśanācca", "And on account of being seen."),
        ("iti cen na parameśvarādhikaraṇam", "If (that object is) this (embodied soul), we deny it, the topic is the highest Lord."),
        ("na prākṛtatvāt", "Not, because it is not a product."),
        ("sambandhāt evam anyatrāpi", "On account of connection, in other passages also."),
        ("śeṣatvāt puruṣārthaḥ syāt", "On account of subsidiary relationship the (result) would be a human purpose."),
        ("viśeṣaṇābhāvācca", "And because of the absence of qualifications."),
        ("tathānyapratiṣedhāt", "On account of the denial of another."),
        ("api ca smaryate", "And it is so mentioned in smṛti."),
        ("śabda iti cen nātaḥ prabhavāt", "If it be said on account of (the word), not so, because (Brahman is) the origin."),
        ("ata eva ca nityatvam", "And from this very reason follows eternality."),
        ("samānāyāṃ ca", "And because there is a similar (text)."),
        ("avirodhaccanduśruteḥ", "And there is no contradiction because of other scriptural texts."),
        ("anyabhāvavyavṛtteśca", "And on account of the negation of a different nature."),
        ("ata eva ca nityatvam", "And from this very reason follows eternality."),
        ("anena sarvagatatvam āyāmaśabdāt", "By this all-pervasiveness, on account of the word indicating extension."),
        ("phalaṃ tatpramāṇatvāt", "The fruit (is) from that, on account of Brahman being the standard."),
        ("uptathyabhāvāditi cet na śabdāt", "If it be said, on account of the absence of the requisite thing, not so, because of the scriptural word."),
        ("anapekṣatvāt na doṣaḥ tathā hi darśayati", "There is no defect, because of the absence of dependence; thus it is shown."),
        ("antaryāmy adhidaivādișu taddharmavyapadeśāt", "The inner ruler (is Brahman), in the divine sphere and so on, because the attributes of that (Brahman) are stated."),
        ("na ca smartamataduktaṃ", "And what is said by smṛti authorities does not teach the same."),
        ("śreyo hi tad tad evopāsanāt", "For that is the most excellent thing, on account of meditations on it."),
        ("tadasarvagatvam", "That is not all-pervasive."),
    ],
    (1,4): [
        ("ānavṛttiḥ śabdādānavṛttiḥ śabdāt", "There is no return, on account of scriptural authority; there is no return, on account of scriptural authority."),
        ("smaryate api ca loke", "And this is also stated in smṛti and in common life."),
        ("darśanācca", "And because it is seen."),
        ("tannirdhāraṇāniyamas taddrṣṭeḥ hyavibhāgaḥ teṣāṃ", "Of that there is no determination; for that it is seen; and the inseparableness of those."),
        ("bhūmā samprasāde'dhyupadeśāt", "The Infinite is the highest Brahman, in the state of deep sleep; on account of teaching."),
        ("dharmopapattescaiva", "And also because the qualities are appropriate."),
        ("na pratiśākhyaṃ", "Not separately stated."),
        ("antarā vijñānamanasī kramagopadhānat", "(Between) vijñāna and manas, on account of the gradual approach of that."),
        ("pramito hi", "For it is limited."),
        ("acharaṃ ca anekaśruteḥ", "And the immovable, on account of many scriptural texts."),
        ("akhyāterapi", "Even though not mentioned."),
        ("brahmadarśanāt", "Because Brahman is seen."),
        ("dharmaupapattesca eva", "And because the qualities are appropriate."),
        ("guṇāt tat vākyāt", "Because of qualities and from that text."),
        ("śabdaviśeṣāt", "On account of a specific word."),
        ("prakāśādivac ca aveśeṣyaṃ prakāśaśca karmanyabhyāsāt", "And because (Brahman is) not different, as in the case of light; and light also, by repetition in the passage."),
        ("ato nānyajaiminiḥ", "Jaimini (thinks) on that account, not different."),
        ("vaiyādhikaraṇyāditi cen na anapekṣitvāt", "If (Jaimini says the two texts belong to) different topics, not so, because of non-dependence."),
        ("api ca smaryate", "And it is also mentioned in smṛti."),
        ("ata eva ca nityatvam", "And from this very reason follows eternality."),
        ("samprasāde anyatamāt", "In the state of deep sleep, among the two, from the other."),
        ("jagadvyāpāravarjam prakraṇāsannihitāt tadvacanāt", "Excluding the government of the world, on account of that being near the beginning of the section, and on account of the text."),
        ("prakāśādivac ca aveśeṣyaṃ", "And because there is no difference, as in the case of light."),
        ("ataḥ prabhavah", "Therefrom is the origin."),
        ("etena yogenāpi", "By this also the yoga (argument is refuted)."),
        ("ātmānam evopalabdha iti tu tatsampradāyāt", "And because scripture teaches the Self (to be obtained), therefore from that teaching."),
        ("na buddhyāderasattā iti cen na pratisedhamatrādhikaraṇam iti", "If it be said that intellect etc. are non-existent, not so; the negation is the present subject."),
        ("api ca evam eke", "And some (teachers) also (hold) thus."),
    ],
    # Adhyāya 2
    (2,1): [
        ("smṛty anapekṣā tadanupapatteriti cen na anyathānumiti kalpanāt", "If it be said that smṛti texts are disregarded (by us), because that (which the smṛti teaches) is impossible, we deny this on account of the hypothesis of a different kind of inference."),
        ("itaraviṣayātvāt arthāt avirodhaśca", "And because (the smṛti) has a different object, and there is no contradiction from the real meaning."),
        ("ata eva ca nityatvam", "And from this same reason eternality."),
        ("aupamyāt", "On account of the comparison."),
        ("yāvaddikṣaṇaṃ tadvyapadeśaḥ", "As long as the qualification lasts, so long the designation."),
        ("etena yogenāpi", "By this the yoga (argument) is refuted."),
        ("na vilakṣaṇatvādasya tathātvam ca śabdāt", "Not on account of its difference, (is it) thus; and because of the scriptural word."),
        ("na tu dṛṣṭāntatvāt", "But not on account of it being a mere illustration."),
        ("svapakṣadoṣācca", "And on account of the defects of their own view."),
        ("tarkāpratiṣṭhānādapi anyathānumeyam iti cen evamapyanirvāhaḥ", "If it be said on account of reasoning having no firm basis, we infer otherwise; we reply that even in that case the difficulty is not removed."),
        ("mahaddīrghavaddhrasvaparimaṇḍalābhyāṃ niyamastulyasatvāt anapekṣatvācca", "The fixing (of size of atoms) is like (the fixing) of large and small (things), on account of equal existence; and on account of independence."),
        ("aśabdaṃ ca", "And the non-scriptural (theory should be rejected)."),
        ("ata eva copamā sūryakādivat", "And for the same reason the comparison (holds good) as in the case of the sun and the rest."),
        ("utkramiṣyata eṣa u eva yah", "This very (Brahman) is what goes out (at death)."),
        ("adarśanāt", "Because of the absence of perception."),
        ("no vilakṣaṇatvādasya tathātvaṃ ca śabdāt", "Not on account of its difference (is it) thus; and because of the scriptural word."),
        ("ata eva cāgnīndhanādivat", "And from this very reason, as in the case of fire and fuel."),
        ("na ca paryāyādapi avirodhastadapyasamañjasam", "But there is no contradiction also on account of the series; but that too is not sound."),
        ("utkramiṣyata eṣa u eva yaḥ", "This very (soul) is what goes out."),
        ("darśanāditi cet naikasyātmatvāt", "If it be said on account of its being seen, not so, because of its being the Self of the one."),
        ("purushartho'taḥ śabdāditi bādariḥ", "The result is for man, from this, by the scriptural word; so Bādari."),
        ("ata eva ca nityatvam", "And from this very reason eternality."),
        ("anyadhidaivādicca evam anyeṣāmapi", "And in the divine sphere and so on, in the same way, for others also."),
        ("api ca evaṃ ke", "And some also (hold it) thus."),
        ("ato nānyajaiminiḥ", "Not another; so Jaimini."),
        ("vaiyādhikaraṇyāditi cen na anapekṣitvāt", "If it be said (the texts belong to) different topics, not so, because of independence."),
        ("na vā prākṛtatvāddhetur ananusandhānāt", "Or rather not, because (the effect is) not a product; because of non-connection."),
        ("api caivaṃ kecid", "And some (teachers) hold thus also."),
        ("etena śiṣṭāparigraho vyākhyātaḥ", "By this the non-acceptance by the educated is explained."),
        ("abhidhyopadeśācca", "And on account of the teaching of meditation."),
        ("akṣarādhiyajñādibhyaśca", "And because of akṣara, adhiyajña, etc."),
        ("api ca smaryate", "And it is so mentioned in smṛti."),
        ("śabda iti cen nātaḥ prabhavāt", "If it be said on account of (the word), not so, because Brahman is the origin."),
        ("yathā ca takṣobhayathā", "And as in the case of the carpenter, on both sides."),
        ("paraṃ tu śrutidṛṣṭaṃ", "But the highest (Brahman) is seen in scripture."),
        ("adṛśyatvādiguṇakodharmaśabdābhāvācca", "And because of the absence of the word 'dharma' for (Brahman) which has such qualities as being invisible."),
        ("viśeṣaṇabhedavyapadeśābhyāṃ ca netaro na'nau", "And because of the distinction of qualification and distinction being stated, not the other two."),
        ("darśayati ca", "And scripture shows."),
    ],
    (2,2): [
        ("raceyanāpatteḥ", "On account of the impossibility of the origination."),
        ("pratisankhyāpratisankhyānirodhāpyanapekṣatvāt", "Because the annihilation (of atoms) also at pralaya does not depend on anything."),
        ("ubhayathāpi na karmātas tad abhāvaḥ", "Either way (the atoms) do not act; therefore there is absence of that."),
        ("abhāvātkarmanāṃ", "On account of the absence of motions."),
        ("prayojakasyāpi na śruter iti cen na anumānāt", "If it be said, not of the mover either, because of scripture; not so, on account of inference."),
        ("bhedābhedau vā", "Or (it is) distinction and non-distinction."),
        ("icchānimithamapyasya amaniśaktatvāt", "The desire also is not a cause for it, on account of inability."),
        ("api ca sarvathā na", "Moreover, in every way, no."),
        ("nāsato'dṛṣṭatvāt", "Not from the non-existent, because it is not seen."),
        ("udāsīnānāmapi caivaṃ siddham", "Thus it is established for those who are impartial also."),
        ("nābhāva upalabdheḥ", "Not non-existence, because of perception."),
        ("vaidharmyācca na svapnādivat", "And on account of difference of character, not as in the case of dream, etc."),
        ("na bhāvo'nupalabdheḥ", "Not existence, because of non-perception."),
        ("kṣaṇikatvācca", "And because of momentariness."),
        ("sarvathānupalabdheśca", "And because it is in no way perceived."),
        ("nityam eva ca bhāvāt", "And (Brahman is) eternal, because of actual existence."),
        ("kāraṇāntaratvāditi cen nāvacanāt", "If it be said, on account of being a different cause; not so, because it is not stated."),
        ("anyatra āhu kevalā", "Elsewhere they say alone."),
        ("samudāya ubhayahetukepi tad anapekṣā", "Even if the aggregate has both as its cause, there is no dependence on that."),
        ("itaretarapratyayatve ca na anyataranityatve", "And if (the two are) mutually dependent, (they are) not eternal separately."),
        ("utpattya asamabhavāt ca", "And because they do not arise simultaneously."),
        ("prayojanavat iti cet syāllokavat", "If it be said (that they act) because of purpose, (we reply) as in common life."),
        ("mahaddīrghavaddhrasvaparimaṇḍalābhyāṃ niyamastulyasatvāt", "The fixing is like large and small, on account of equal existence."),
        ("anapekṣatvācca", "And because of independence."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("abdhyupadeśācca", "And because of the teaching about the ocean."),
        ("ataeva cāgnīndhanādivat", "And for this reason, as fire and fuel."),
        ("samānaḥ cāsaṃgatyāt", "And the same on account of lack of connection."),
        ("na tṛtīye tathopalabdheḥ", "Not in the third, because it is seen thus."),
        ("etena mātariśvā vyākhyātaḥ", "By this, mātariśvā is explained."),
        ("abhyupagame'pyarthasampadāt", "Even if conceded, (the result is) from the real meaning."),
        ("puruṣāśmavaditi cen na vikārādibhyaḥ", "If it be said (the result is) as in the case of a person and a stone, not so, because of modification, etc."),
        ("aṅgitvānupapatteśca na darśayati hi", "And because it is impossible for it to be the main thing; and scripture does not show."),
        ("anumānaṃ ca aśabdamiti cenna śabdādibhyaḥ", "And the inference also is non-scriptural; not so, because of scriptural texts and the rest."),
        ("anyathānumitau ca jaiminiḥ", "If otherwise inferred, so Jaimini."),
        ("samānāyāṃ ca", "And because of a similar text."),
        ("na ca paryāyādapi avirodhastadapyasamañjasam", "There is no contradiction from sequence either; but that too is unsound."),
        ("anyadhidaivādicca", "And in the divine sphere, etc."),
        ("api ca smaryate", "And it is also mentioned in smṛti."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("śabda iti cen nātaḥ prabhavāt", "If it be said on account of the word; not so, because Brahman is the origin."),
        ("sthānādibyaśca", "And on account of place and the rest."),
        ("saṃhārāya", "For dissolution."),
        ("na vilakṣaṇatvādasya tathātvaṃ ca śabdāt", "Not on account of difference; and because of the scriptural word."),
    ],
    (2,3): [
        ("na vāyukriye pṛthagupadeśāt", "Not air and action, because of separate teaching."),
        ("chakṣuṣādivat tu tatsahaśiṣṭyādibhyaḥ", "But as with the eye and so on, on account of being taught together with that, etc."),
        ("akaraṇatvācca na doṣastathā hi darśayati", "And because there is no origination; there is therefore no defect; thus it is shown."),
        ("pañcavṛttirmanuvadviśeṣaḥ", "The fivefold (division of prāṇa) is a particular distinction, as in the case of manu."),
        ("aṇuścatathā darśanāt", "And the soul is atomic in size, because it is seen thus."),
        ("śrutatvācca", "And because of scriptural statement."),
        ("tadbhāvabhāvittva ca", "And because becoming follows on the becoming of that."),
        ("na śabdādibhyo'ntaḥpratiṣṭhānāt neti cen na tathā dṛṣṭyupadeśādaśabdavacca", "Not from sound and the rest, because they subsist within; if it be said, not so, because of the teaching of seeing thus, and because of the word."),
        ("jñasphurtyabhiprāya vibhūtvakāmaśca", "The meaning is manifestation of the knower; and pervasiveness is the intention."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("utpattimasambhavāt", "Origination is impossible."),
        ("na ca kāryātmaikyam", "And the effect is not identical (with the cause)."),
        ("aśabdaṃ ca", "And (it is) non-scriptural."),
        ("parāt tu tacchrutes tanmātram", "But from the highest, because it is stated; only that."),
        ("tadvyatirekeṇa anavastitescānyatamābhāvāt", "And because of its non-existence distinct from that; and because of the absence of one of the two."),
        ("abhāvaṃ bādariāha hyevam", "Bādari says non-existence; for thus (scripture states)."),
        ("bhāvaṃ jaiminirvipratipatteḥ syāt", "Jaimini (says) existence, because of contradictory (statements)."),
        ("auḍulomistu naivaṃ tathānyeṣāmapi darśanāt", "But Auḍulomi (holds) it is not thus, because the view of others also is seen."),
        ("kāryākhyānādapūrvaṃ", "From the statement of the effect; what did not exist before."),
        ("pramitastatpāramparye na ca tasya tadātmatvam", "It is measured; in the succession of that; and there is no identity with it."),
        ("bhāveccopalabdheḥ", "And on account of perception in existence."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("sat iti cen naikasyātmatvāt", "If it be said (it is) existent, not so, because of its being the Self of one."),
        ("nityopalabdhyanupalabdhiprasaṅgo'nyataraniyamo vānyathā", "Otherwise there would result either eternal perception or eternal non-perception, or the fixity of one; or otherwise."),
        ("vāyavadvyaṣṭisamaṣṭyoḥ", "As in the case of air, (in) the individual and the collective."),
        ("pṛthag upadeśāt", "Because of separate teaching."),
        ("tathānye", "Thus others."),
        ("aśabdaṃ ca", "And (it is) non-scriptural."),
        ("tat karmitayā evaśabdāt", "Because of the word indicating the soul as doing that work."),
        ("darśanāditi cet naikasyātmatvāt", "If it be said from being seen; not so, because it is the Self of one."),
        ("pratyakṣopadeśāditi cet nādhikārikamandalaṃstha deva uvāca", "If it be said on account of direct scriptural statement; not so; the god spoke (the teaching) for those qualified."),
        ("yāvaddikṣaṇaṃ tadvyapadeśaḥ", "As long as the qualification lasts, so long the designation."),
        ("śabdādeva pramitaḥ", "It is measured by scripture alone."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("vibhāgo vacanāt", "Separation because of the word."),
        ("tathā copalabdheḥ", "And because of perception being thus."),
        ("karmādhikaraṇatvam", "The relation of substratum to action."),
        ("saptānnā brahmano vicāraṃ", "The seven foods are Brahman's."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("amuṃ vyomatatvam", "That has the nature of ether."),
        ("ātmā", "The Self."),
        ("darśanācca", "And because of being seen."),
        ("iti cenna parameśvarādhikaraṇam", "If this (is the individual soul); not so; the topic is the highest Lord."),
        ("api ca evam eke", "And some also (hold it) thus."),
        ("asminnasya ca tadyogaṃ śāsti", "And scripture teaches the relation of this to that."),
    ],
    (2,4): [
        ("tathā prāṇāḥ", "So also the prāṇas (proceed from Brahman)."),
        ("gauṇaścennātmaśabdāt", "If in a secondary sense, not so, because of the word 'Self.'"),
        ("etena prāṇādayo vyākhyātāḥ saptānnā brahmano vicāraṃ", "By this the prāṇas and others are explained; the seven foods are Brahman's."),
        ("akaraṇatvācca na doṣastathā hi darśayati", "And because of non-origination; there is no defect; thus it is shown."),
        ("pañcavṛttirmanuvadviciśeṣaḥ", "The fivefold is a distinction as in the case of manu."),
        ("aṇuścatathā darśanāt", "And the (prāṇa) is atomic, because it is seen thus."),
        ("jyotiryalayagatyābhidhānāt", "On account of the mention of light, non-going and going."),
        ("tacchrutes", "Because of that being stated in scripture."),
        ("bhedaśruteḥ", "On account of the scripture teaching distinction."),
        ("vaiśeṣyāt tu tadvādastu bhāvabhāvitvāt", "But because of distinction; that statement; because becoming follows on the becoming of that."),
        ("anukṛtes tasya ca", "And of that (prāṇa) on account of imitation."),
        ("saptānnā brahmano vicāraṃ", "The seven foods are Brahman's."),
        ("ata eva ca nityatvam", "And from this same reason, eternality."),
    ],
    # Adhyāya 3
    (3,1): [
        ("tad antaḥ pratiṣṭhānāt tu", "But on account of its subsisting within."),
        ("bhūmā samprasāde", "Brahman is the largest, in deep sleep."),
        ("tad vyapadeśāt anya eva na arthaśabdatvāt", "Because of the designation of that, it is another; not so, because of the meaning of the word."),
        ("asminnasya ca tadyogaṃ śāsti", "And scripture teaches the relation of this to that."),
        ("prakaraṇāt", "On account of context."),
        ("taddhetuvyapadeśācca", "And because of its being stated as the cause."),
        ("manastuvyākhyātam", "But the mind has been explained."),
        ("api ca smaryate", "And this is also mentioned in smṛti."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("amuṃ vyomatatvam", "That has the nature of ether."),
        ("darśanāt", "Because it is seen."),
        ("etenasarvagatatvam āyāmaśabdāt", "By this all-pervasiveness, on account of the word indicating extension."),
        ("phalaṃ tatpramāṇatvāt", "The fruit (is) from that, Brahman being the measure."),
        ("anapekṣatvācca", "And because of independence."),
        ("antaḥ taddharmopaddeśāt", "The inner (Self), because of the statement of the attributes of that."),
        ("bhedavyapadeśācca", "And because of distinction being mentioned."),
        ("prāṇastattvam", "Prāṇa is that Brahman."),
        ("śabdaviśeṣāt", "On account of a specific word."),
        ("hānāu tūpāyanambhyāsāt", "On removal, on account of teaching of union."),
        ("adarśanānneti cen naikasya ubhayathā", "If it be said, not seen; not so, because for one both (are possible)."),
        ("karyakhyanadapurvam", "From the statement of the effect; what did not exist before."),
        ("samānāyāṃ ca", "And because of a like (text)."),
        ("etena yogaḥ pratyuktaḥ", "By this, yoga is refuted."),
        ("na tṛtīye tathopalabdheḥ", "Not in the third, because it is thus seen."),
        ("na ca smartamataduktaṃ", "And what smṛti authorities say does not teach the same."),
        ("na ca kāryātmaikyam", "And the effect is not identical."),
        ("anutāpādivat", "As in the case of regret and so on."),
        ("aupamyāt", "On account of comparison."),
        ("taddhetuvyapadeśācca", "And because of its being stated as the cause."),
        ("anusmṛterātmadṛṣṭau taddarśanāt", "On account of remembrance through self-perception; it is so seen."),
        ("ubhayathā ca doṣāt tad api na", "And because of defects in both ways, that also not."),
        ("tasya api nirodhaḥ pāramparye", "The suppression of that also in succession."),
        ("sarvatha api taeva ubhayalingam", "In every way also, the same has both characteristics."),
        ("anapekṣatvācca", "And because of independence."),
        ("anyathānumanamiti cet evam apy anirvāhaḥ", "If it be said inference otherwise; even so, there is no issue."),
        ("niti cen nāntaratvāt", "If not; not so, because of being internal."),
        ("tathā api na", "Even so, not."),
        ("pratiṣedhāt", "Because of negation."),
        ("sarvadharmopapattescaiva", "And because all qualities are appropriate."),
        ("yathā ca takṣobhayathā", "And as in the case of the carpenter, on both sides."),
        ("paraṃ tu śrutidṛṣṭaṃ", "But the highest is seen in scripture."),
        ("atyantāṃ", "At the extreme."),
        ("pūrvaṃ tu badarāyaṇo hetur vyāpadeśāt", "But the earlier (relation) Bādarāyaṇa (considers), because of purpose being stated."),
    ],
    (3,2): [
        ("sandhye sṛṣṭirāha hi", "In the intermediate state there is creation; for scripture says so."),
        ("nirmmāṇam ātmanaḥ", "The creation is of the Self."),
        ("parasya ubhayathā api dṛṣṭam atṛptikāmitā", "Both are seen in the case of the highest; (and) the desire for what is not satiated."),
        ("prakāśavaccāvaişeşyaṃ", "And because (the Lord is) not different from it, as in the case of light."),
        ("vaidharmyācca na svapnādivat", "And on account of difference of nature, not as in dream, etc."),
        ("na bhedasruteh", "Not so, because of scriptural distinction."),
        ("vā śabdādibhyaḥ antaḥpratiṣṭhānāt", "Or on account of scriptural texts and the rest; because of residing within."),
        ("sarvabhāvāt", "Because of being everything."),
        ("ato'nantena tathā hi lingam", "Thus from the infinite; thus indeed the mark."),
        ("ubhayavyāpadeśāt tu ahikuṇḍalavat", "But on account of both being stated, as in the case of a snake and its coils."),
        ("prakāśāśrayavadva", "Or as the abode of light."),
        ("uttare ca", "And in the sequel."),
        ("anena sarvagatatvam āyāmaśabdāt", "By this all-pervasiveness; on account of the word indicating extension."),
        ("phalaṃ tatpramāṇatvāt", "The fruit (is) from that, Brahman being the measure."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("śabda iti cen nātaḥ prabhavāt", "If it be said on account of the word; not so, because Brahman is the origin."),
        ("tannirdhāraṇāniyamas taddrṣṭeḥ hyavibhāgaḥ teṣāṃ", "There is no fixity for that determination; because that is seen; and their inseparableness."),
        ("anena sarvagatatvamāyāmaśabdāt", "By this all-pervasiveness; on account of the word indicating extension."),
        ("nāsato'dṛṣṭatvāt", "Not from the non-existent, because it is not seen."),
        ("bhāvaccopalabdheḥ", "And because of perception in existence."),
        ("aśabdaṃ ca", "And it is non-scriptural."),
        ("akaraṇatvācca na doṣastathā hi darśayati", "And because of absence of origination; no defect; thus indeed it is shown."),
        ("viśeṣaṇabhedavyapadeśābhyāṃ ca netaro nānau", "And because distinction of qualifier and distinction are stated; not the other two."),
        ("darśayati ca", "And it is shown."),
        ("api ca smaryate", "And it is also stated in smṛti."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("smṛtibhyaśca", "And from smṛti texts."),
        ("anyadhidaivādicca evam anyeṣāmapi", "And in the divine sphere etc., in the same way, for others also."),
        ("api ca evaṃ kecit", "And some also (hold it) thus."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("anena yogenāpi", "By this also through yoga."),
        ("asamañjasam jaiminiḥ", "Jaimini considers it unsound."),
        ("na ca paryāyādapi avirodhastadapyasamañjasam", "There is no contradiction from sequence either; but that too is not sound."),
        ("ato nānyajaiminiḥ", "Not another; so Jaimini."),
        ("vaiyādhikaraṇyāditi cen na anapekṣitvāt", "If it be said different topics; not so; on account of independence."),
        ("adarśanān neti cen naikasya ubhayathā", "If not seen; not so; for one both (are possible)."),
        ("etenasarvagatatvam", "By this, all-pervasiveness."),
        ("phalaṃ tatpramāṇatvāt", "The fruit from that, Brahman being the measure."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("pratiṣṭhitayorjñānadīptiśca", "And the luminosity of knowledge for those established."),
        ("tadabhāvāt", "On account of the absence of that."),
    ],
    (3,3): [
        ("sarvavedānta pratyayaṃ codanādyaviśeṣāt", "There is one aim of all Vedānta texts, on account of the uniformity of injunction etc."),
        ("bhedānneti cen naikasya ubhayathā", "If on account of difference, not so; for one both are possible."),
        ("svādhyāyasya tathaivetvam āśamanikāyāṃ bodhanāt", "And the same for one's own study; because of teaching in the Āśamanikā."),
        ("darśayati ca", "And scripture shows."),
        ("upasaṃhāras tadbhāvāt niyame cet sarvavarūpāṇāmeva", "The reference is to that, on account of being thus; if (there are) restrictions, (they apply) to all forms."),
        ("antenāśrayitveṇa jaiminiratha taṃ vinā jaiminihikaraṇāt", "At the end, Jaimini (considers the soul) to be of a holding nature; for that reason Jaimini's separate treatment."),
        ("kṛtsnaprasaktir nirāvaraṇasyānyeṣāmapi darśanāt", "But the unrestricted (soul) has (the power of moving) through everything, because it is so seen for others also."),
        ("na ca paryāyādapi avirodhastadapyasamañjasam", "There is no contradiction on account of succession either; but that too is unsound."),
        ("etena yogaḥ pratyuktaḥ", "By this the yoga is refuted."),
        ("abhidhyopadeśācca", "And on account of the teaching of meditation."),
        ("visheṣaṇabhedavyapadeśābhyāṃ ca netaro nānau", "And because distinction of qualifier and distinction are stated; not the other two."),
        ("tanniṣṭhasya mokṣopadeśāt", "On account of the teaching of liberation for one devoted to that."),
        ("taddhetuvyapadeśācca", "And because of its being stated as the cause."),
        ("manastuvyākhyātam", "But the mind has been explained."),
        ("jagadvyāpāravarjaṃ", "Excluding the government of the world."),
        ("prakaraṇāt", "On account of context."),
        ("ato'nantena tathā hi lingam", "Thus from the infinite; thus indeed the mark."),
        ("ubhayavyāpadeśāt tu ahikuṇḍalavat", "But on account of both being stated, as snake and coils."),
        ("prakāśāśrayavadva", "Or as the abode of light."),
        ("uttare ca", "And in the sequel."),
        ("tadvyatirekeṇa anavastiteśca anyatamābhāvāt", "And because of non-existence distinct from that; and because of the absence of one."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("amuṃ vyomatatvam", "That has the nature of ether."),
        ("ātmā", "The Self."),
        ("darśanāt", "Because it is seen."),
        ("iti cenna parameśvarādhikaraṇam", "If this; not so; the topic is the highest Lord."),
        ("abhivyaktivyapadeśācca", "And because of the statement of manifestation."),
        ("yathevaṃ ca na śabdataḥ dṛṣṭatvāt", "And as thus, not on account of the word; because it is seen."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("sarvāpekṣā ca yajñādiśrutervavanmānāt", "And the dependence on all is known from the scriptural texts about sacrifice etc., by comparison."),
        ("śrutyuktābhyāṃ guṇadvayācca", "And because of the two qualities mentioned in scripture."),
        ("smṛtibhyaśca", "And from smṛti texts."),
        ("anyadhidaivādicca evam anyeṣāmapi", "And in the divine sphere etc., in the same way, for others also."),
        ("api ca evaṃ ke", "And some also (hold it) thus."),
        ("etenottara api vyākhyātāḥ", "By this the higher ones also are explained."),
        ("yāvaddikṣaṇaṃ tadvyapadeśaḥ", "As long as the qualification, so long the designation."),
        ("vikṛtaḥ avare tathaiva", "Modified; for the lower ones; in the same way."),
        ("darśanācca", "And because it is seen."),
        ("na sarvaprakṛtiḥ svabhāvācca", "Not all; (it is) from nature."),
        ("na ca paryāyādapi avirodhastadapyasamañjasam", "There is no contradiction from sequence either; and that too is unsound."),
        ("anena yogaḥ pratyuktaḥ", "By this yoga is refuted."),
        ("nāsato'dṛṣṭatvāt", "Not from the non-existent, because it is not seen."),
        ("vaidharmyācca na svapnādivat", "And on account of difference of nature, not as in dream."),
        ("aśabdaṃ ca", "And it is non-scriptural."),
        ("viśeṣaṇabheda vyapadeśābhyāṃ ca netaro nānau", "And because qualification-distinction and distinction are stated; not the other two."),
        ("darśayati ca", "And it is shown."),
        ("api ca evaṃ kecit", "And some also (hold it) thus."),
        ("ato nānyajaiminiḥ", "Not another; so Jaimini."),
        ("vaiyādhikaraṇyāditi cen na anapekṣitvāt", "If it be said different topics; not so; on account of independence."),
        ("adarśanān neti cen naikasya ubhayathā", "If not seen; not so; for one both are possible."),
        ("śabdādeva pramitaḥ", "It is measured by scripture alone."),
    ],
    (3,4): [
        ("puruṣārtho'taḥ śabdāditi bādariḥ", "For man's sake; thus from scripture; so Bādari."),
        ("śeṣatvāt puruṣārthaḥ syāt", "On account of subsidiary relation, there would be a human purpose."),
        ("ācāradarśanāt", "On account of the perception of conduct."),
        ("tasmai api nityadarśanāt", "For that also on account of eternal perception."),
        ("bhāvaccopalabdheḥ", "And because of perception in existence."),
        ("samārambhaṇaśabdādibhyaśca", "And on account of such scriptural words as 'taking up.'"),
        ("yāvaddikṣaṇaṃ tadvyapadeśaḥ", "As long as the qualification, so long the designation."),
        ("taddhetuvyapadeśācca", "And on account of its being stated as the cause."),
        ("śrutatvācca", "And because of its being stated in scripture."),
        ("sarvāpekṣā ca yajñādiśruteraśvavat mānāt", "And the dependence on all (is known) from the scriptural texts about sacrifice, by comparison to horse."),
        ("etena śiṣṭāparigraho vyākhyātaḥ", "By this the non-acceptance by the educated is explained."),
        ("tanniṣṭhasya mokṣopadeśāt", "On account of the teaching of liberation to one devoted to that."),
        ("nāvisheṣo janādiva na ca tacchreyasyanuvṛttiḥ", "There is no difference, as from men; and following that which is highest is not (found)."),
        ("ato'nyāpi hyekeṣāmubhayoḥ", "Because also for some, both of these."),
        ("viśeṣaṇābhāvācca", "And because of the absence of qualifications."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
    ],
    # Adhyāya 4
    (4,1): [
        ("āvṛttirasaktidoṣaddarśanāt", "Repetition (of meditation) on account of the teaching of connection (with Brahman)."),
        ("āditya ādau matparyāye cātaḥ", "From the sun at the start; on account of the relation to me; and from this."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("smaryate api ca loke", "And it is mentioned in smṛti and in common life."),
        ("tadbhāvabhāvitvāt", "Because becoming follows on the becoming of that."),
        ("nirāvastukatvāt karma", "The action has no (additional) basis."),
        ("etena yogaḥ pratyuktaḥ", "By this, yoga is refuted."),
        ("anyadhidaivādicca evam anyeṣāmapi", "And in the divine sphere etc., in the same way, for others also."),
        ("na pūrvabhāvāt", "Not on account of the previous existence."),
        ("karmādhikaraṇatvam", "The relation of substratum to action."),
        ("na ca kāryātmaikyam", "And the effect is not identical."),
        ("ato'nyāpi hyekeṣāmubhayoḥ", "Because also for some, both."),
        ("na vilakṣaṇatvādasya tathātvaṃ ca śabdāt", "Not on account of difference; and because of the word."),
        ("yathā ca takṣobhayathā", "And as in the case of the carpenter, on both sides."),
        ("paraṃ tu śruter dṛṣṭam", "But the highest is seen in scripture."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("smṛtyarthaṃ ca", "And for the purpose of smṛti."),
        ("tatsahetukatvāt ubhayoḥ", "Because it is the cause for both."),
        ("darśanācca", "And because it is seen."),
        ("aśabdaṃ ca", "And it is non-scriptural."),
        ("antarā vijñānamanasī kramagopadhānat", "Between vijñāna and manas, on account of the gradual approach."),
    ],
    (4,2): [
        ("tasyaiva ca niyamāt", "And because of the rule for him (alone)."),
        ("aśabdaṃ ca", "And it is non-scriptural."),
        ("nābhāva upalabdheḥ", "Not non-existence, because of perception."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("āśrayānupapatteśca", "And because support is impossible."),
        ("utkrāntigatimāgatīnāṃ", "Of going out, going and coming."),
        ("svādhyāyasya tathaivetvam āśamanikāyāṃ bodhanāt", "And the same for one's own study; because of teaching in the Āśamanikā."),
        ("na ca smartamataduktaṃ", "And what smṛti authorities say does not state the same."),
        ("smṛtibhyaśca", "And from smṛti texts."),
        ("darśanācca", "And because it is seen."),
        ("tannirdhāraṇāniyamas taddrṣṭeḥ hyavibhāgaḥ teṣāṃ", "No determination of that; because that is seen; and their inseparableness."),
        ("abhidhyopadeśācca", "And on account of the teaching of meditation."),
        ("visheṣaṇabhedavyapadeśābhyāṃ ca netaro nānau", "And because distinction of qualifier and distinction are stated; not the other two."),
        ("kāmācca nānumānāpekṣā", "And on account of desire, there is no need of inference."),
        ("darśayati ca", "And it is shown."),
        ("api ca evaṃ ke", "And some also (hold it) thus."),
    ],
    (4,3): [
        ("tadokograjvalanaṃ tatprakāśitadvāro vidyāsāmarthy āt tac cheṣagaty anusmṛtiyog ācca", "The blazing up of the nerves, the door opened by it, on account of the power of knowledge; and on account of the remembrance of connection with the path."),
        ("rśmayanusārī", "Following the rays."),
        ("niśi neti cen na sambandhasya yāvaddehabhāvitvāddarśayati ca", "Not at night; not so; because the connection lasts as long as the body; and it is shown."),
        ("ataścāyane'pi dakṣiṇe", "And thus also on the southern path."),
        ("yoginaḥ prati smaryate smārte caite", "For the yogin it is mentioned in smṛti; and these (are) of the smṛti (kind)."),
        ("tasmāddvyayoḥ prāpto ityupagamāt", "Therefore of the two, (one) having obtained, by accepting."),
        ("tadadhigame'pi tattulye ca tat", "Even on attaining that, (it is) the same for the equal; and thus."),
        ("cakṣuṣā tattvāt", "On account of its being thus because of the eye."),
        ("ādityo'nūyāti", "The sun follows."),
        ("tasmāddevā", "Therefore the gods."),
        ("sā eva ca tayor darśanāt", "And the same for those two; because it is seen."),
        ("tathā anyeṣāmapi", "In the same way for others also."),
        ("ata eva ca nityatvam", "And from this very reason, eternality."),
        ("abhivyaktivyapadeśācca", "And because of the statement of manifestation."),
        ("ānavṛttiḥ śabdād ānavṛttiḥ śabdāt", "No return, by scripture; no return, by scripture."),
    ],
    (4,4): [
        ("sampadyāvirbhāvaḥ svena śabdāt", "On attainment, manifestation in one's own (form); because of the word."),
        ("muktaḥ pratijñānāt", "Liberation is promised."),
        ("ātmā prākaraṇāt", "The Self, on account of context."),
        ("avirodhaḥ candanavat", "No contradiction, as in the case of sandal."),
        ("prāde śamātraṃ hi pratiśedhati tata evā ca viśeṣaḥ", "For it denies only a little; and from that very (text comes) the distinction."),
        ("sa eva tu karmānusmṛtiśabdavidhyabhāsāt", "But the same (Brahman on account of the injunction being a secondary meaning of karma), memory, word (and) enjoining."),
        ("nānumānaṃ atacchabdāt pravṛttescaiva", "Not inference, because the word is not that; and because of inclination."),
        ("darśanācca ata eva hi nityatvam", "And because it is seen; therefore indeed eternality."),
        ("bhāvaccopalabdheḥ", "And because of perception in existence."),
        ("prakaraṇāt", "On account of context."),
        ("phalaṃ tatpramāṇatvāt", "The fruit from that, Brahman being the measure."),
        ("śrutatvācca", "And because of scriptural statement."),
        ("ekasya ubhayeṣāṃ tadvyapadeśācca karmāṇi", "For one; for both; because of its being stated thus; and actions."),
        ("vikṣepāvyapadeśācca", "And because of the statement of dispelling."),
        ("taduktam", "That has been stated."),
        ("bhogamātra sāmya liṅgācca", "And on account of the indication of equality (with Brahman) only in enjoyment."),
        ("anapratiṣṭhitaḥ", "Not having (additional) support."),
        ("jagadvyāpāravarjaṃ prakaraṇāt asannihitāt tadvacanāt ca", "Excluding the administration of the world; on account of context; because it is not nearby; and on account of the text."),
        ("pratyakṣopadeśāditi cet nādhikārikam maṇḍalastha deva uvāca", "If on account of direct scriptural teaching; not so; it is for the qualified; the god dwelling in the orb spoke."),
        ("vikṛtaḥ avare tathaiva", "Modified; for the lower ones; in the same way."),
        ("darśanācca", "And because it is seen."),
        ("tad abhāvān neti cen na upalabdheḥ", "If on account of absence of that, not; not so, because of perception."),
    ],
}

ADH_NAMES = {1: "Adhyāya 1 — Samanvaya", 2: "Adhyāya 2 — Avirodha", 3: "Adhyāya 3 — Sādhana", 4: "Adhyāya 4 — Phala"}

def build_verses():
    verses = []
    n = 1
    for (adh, pada), sutras in sorted(SUTRAS.items()):
        adh_label = ADH_NAMES[adh]
        sec = f"Pāda {pada}"
        for i, (iast_text, trans_text) in enumerate(sutras, 1):
            dev_text = dev(iast_text)
            verses.append({
                "ref": str(n),
                "adh": adh_label,
                "sec": sec,
                "dev": dev_text,
                "iast": iast_text,
                "trans": trans_text,
                "commentaries": {}
            })
            n += 1
    return verses

def main():
    verses = build_verses()
    data = {
        "id": "brahmasutra",
        "title": "Brahmasūtras",
        "titleDeva": "ब्रह्मसूत्राणि",
        "titleEnglish": "Brahma Sutras (Vedanta Sutras)",
        "veda": "Vedānta",
        "verses": verses
    }
    out = os.path.join(os.path.dirname(__file__), '..', 'public', 'content', 'upanishads', 'brahmasutra.json')
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(verses)} sūtras → {out}")

if __name__ == '__main__':
    main()
